# Generated by Django 4.1.6 on 2023-02-16 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_rename_login_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth',
        ),
    ]
