# Generated by Django 4.1.6 on 2023-02-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user_coach',
        ),
    ]
