# Generated by Django 4.1.6 on 2023-03-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_coordinator_delete_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='phone',
            new_name='contact_info',
        ),
    ]
