# Generated by Django 4.1.6 on 2023-03-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0011_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user_type', models.CharField(max_length=100)),
            ],
        ),
    ]
