# Generated by Django 4.1.6 on 2023-03-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_user_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='c_id',
            new_name='coordinator',
        ),
    ]
