# Generated by Django 4.1.6 on 2023-03-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_rename_c_id_event_coordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinator',
            old_name='sports_type',
            new_name='sport_type',
        ),
    ]
