# Generated by Django 4.1.6 on 2023-03-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0015_sponsor_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('matches_played', models.IntegerField()),
                ('matches_won', models.IntegerField()),
                ('matches_lost', models.IntegerField()),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_time', models.TimeField()),
                ('location', models.CharField(max_length=60)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coordinator')),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.event')),
            ],
        ),
        migrations.CreateModel(
            name='football_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=10)),
                ('contact_info', models.CharField(max_length=20)),
                ('strong_foot', models.CharField(max_length=10)),
                ('matches_played', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('highest_goal_score', models.IntegerField()),
                ('cards', models.CharField(max_length=100)),
                ('achievements', models.CharField(max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.cricket')),
            ],
        ),
        migrations.CreateModel(
            name='football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('matches_played', models.IntegerField()),
                ('matches_won', models.IntegerField()),
                ('matches_lost', models.IntegerField()),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coordinator')),
            ],
        ),
        migrations.CreateModel(
            name='cricket_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=10)),
                ('contact_info', models.CharField(max_length=20)),
                ('batting_style', models.CharField(max_length=10)),
                ('bowling_Style', models.CharField(max_length=10)),
                ('matches_played', models.IntegerField()),
                ('runs_scored', models.IntegerField()),
                ('wickets_taken', models.IntegerField()),
                ('highest_score', models.IntegerField()),
                ('highest_wicket', models.IntegerField()),
                ('achievements', models.CharField(max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.cricket')),
            ],
        ),
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spending', models.CharField(max_length=20)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.event')),
            ],
        ),
    ]
