# Generated by Django 4.1.6 on 2023-03-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0016_cricket_training_football_performance_football_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(max_length=20)),
                ('opponent', models.CharField(max_length=60)),
                ('final_score', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('achievements', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem_details', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=20)),
                ('recovery_status', models.CharField(max_length=100)),
            ],
        ),
    ]
