# Generated by Django 4.1.6 on 2023-03-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0017_history_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sponsor',
            field=models.CharField(max_length=100),
        ),
    ]
