# Generated by Django 4.1.6 on 2023-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0018_alter_inventory_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
