# Generated by Django 4.1.6 on 2023-03-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0020_alter_cricket_performance_batting_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricket_performance',
            name='achievements',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='football_performance',
            name='achievements',
            field=models.IntegerField(),
        ),
    ]
