# Generated by Django 4.1.6 on 2023-03-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0021_alter_cricket_performance_achievements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('achievement_details', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
