# Generated by Django 4.1.6 on 2023-03-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0022_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='cricket_performance',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='football_performance',
            name='achievements',
        ),
        migrations.AddField(
            model_name='achievements',
            name='player_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
