# Generated by Django 4.1.6 on 2023-03-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0023_remove_achievements_player_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='event_name',
        ),
        migrations.AddField(
            model_name='training',
            name='details',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='team_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
