# Generated by Django 4.1.6 on 2023-03-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0026_alter_football_performance_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievements',
            old_name='achievement_details',
            new_name='achievement',
        ),
    ]
