# Generated by Django 4.1.6 on 2023-03-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0027_rename_achievement_details_achievements_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricket_performance',
            name='batting_style',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cricket_performance',
            name='bowling_Style',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cricket_performance',
            name='contact_info',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cricket_performance',
            name='highest_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cricket_performance',
            name='highest_wicket',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cricket_performance',
            name='matches_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cricket_performance',
            name='player_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cricket_performance',
            name='role',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cricket_performance',
            name='runs_scored',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cricket_performance',
            name='wickets_taken',
            field=models.IntegerField(null=True),
        ),
    ]
