# Generated by Django 4.1.6 on 2023-03-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0028_alter_cricket_performance_batting_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='football_performance',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='football_performance',
            name='cards',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='football_performance',
            name='contact_info',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='football_performance',
            name='goals_scored',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='football_performance',
            name='highest_goal_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='football_performance',
            name='matches_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='football_performance',
            name='player_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='football_performance',
            name='position',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='football_performance',
            name='strong_foot',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
