# Generated by Django 4.1.6 on 2023-03-31 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0029_alter_football_performance_assists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='achievements',
        ),
    ]
