# Generated by Django 4.1.6 on 2023-03-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0031_history_opponent_score_history_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='event_name',
            field=models.CharField(max_length=267, null=True),
        ),
    ]
