# Generated by Django 4.1.6 on 2023-04-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0032_budget_date_budget_location_alter_budget_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
