# Generated by Django 4.1.6 on 2023-04-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0033_problem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='event_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
