# Generated by Django 4.1.6 on 2023-04-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0035_remove_history_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='recovery_status',
            field=models.DateField(),
        ),
    ]
