# Generated by Django 4.1.6 on 2023-04-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0037_rename_cards_football_performance_red_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_auth',
            name='name',
            field=models.CharField(max_length=298, null=True),
        ),
    ]
