# Generated by Django 4.1.6 on 2023-04-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0038_user_auth_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='details',
            field=models.CharField(max_length=289),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
