# Generated by Django 4.1.6 on 2023-05-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0039_alter_sponsor_details_alter_sponsor_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricket',
            name='matches_lost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cricket',
            name='matches_won',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='football',
            name='matches_lost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='football',
            name='matches_won',
            field=models.IntegerField(null=True),
        ),
    ]
