# Generated by Django 4.1.6 on 2023-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0042_rename_bowling_style_cricket_performance_bowling_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='football_performance',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
