# Generated by Django 4.1.6 on 2023-05-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0045_alter_problem_recovery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_auth',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
