# Generated by Django 4.1.6 on 2023-05-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0046_alter_user_auth_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase_date',
            field=models.CharField(max_length=20),
        ),
    ]
