# Generated by Django 4.1.6 on 2023-05-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0047_alter_inventory_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='reporting_time',
            field=models.CharField(max_length=10),
        ),
    ]
