# Generated by Django 4.1.6 on 2023-05-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0049_football_individual_cricket_individual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cricket_individual',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='cricket_individual',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='cricket_individual',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='football_individual',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='football_individual',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='football_individual',
            old_name='team_id',
            new_name='team',
        ),
    ]
