# Generated by Django 4.1.6 on 2023-05-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0050_rename_match_id_cricket_individual_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricket_individual',
            name='match',
        ),
        migrations.RemoveField(
            model_name='football_individual',
            name='match',
        ),
    ]
