# Generated by Django 4.1.6 on 2023-05-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0051_remove_cricket_individual_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricket_individual',
            name='team',
        ),
        migrations.RemoveField(
            model_name='football_individual',
            name='team',
        ),
    ]
